server:
  port: 9090
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/thy
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update