server:
  port: 9090
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/um
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: tureraosantosh@gmail.com
    password: Mumbai@123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
app:
  messages:
    welcomeMsg: Welcome To Career Infotech
    greet: Greet The One
    invalidCredentials: Invalid Credentials !
    accountLocked: Your Account is Locked  !
    success: You have logged in successfully.
    userRegSuccess: Please Check Your Email For Unlocking Your Account
    userRegFail: Failed To Register
    unlockAccEmailSub: Registration Success| Career Infotech
    unLockEmailFileName: UNLOACK-EMAIL.txt
    recoverPwdEmailFileName: RECOVERY-EMAIL.txt
    recoverAccEmailSub: Email Recoverd Success| Career Infotech